### ISSUE TITLE
Deprecation for Ember 2.18.2

### ISSUE THREAD

**Issue by mongeta** [AmilKey/ember-i18n-iso-countries#5]
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   DependencyVersionChecker.NPMDependencyVersionChecker (/Users/xxxxxx/Developer/Ember/xxxxxx/node_modules/ember-i18n-iso-countries/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:32)

Current version: 1.4.0

**Comment by scottkidder** [comment]
Fixed in #6
