### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by scottkidder** [AmilKey/ember-i18n-iso-countries#7]
@AmilKey Maybe time for a release?

**Comment by scottkidder** [comment]
@AmilKey I see that 1.5.0 is listed as a release here on github, but package.json and npm still think 1.4.0.

**Comment by simonc** [comment]
Hi there, I was also interested in v1.5. @AmilKey is there anything preventing a release on npm? If so can we be of any help? Thanks! ❤️

**Comment by AmilKey** [comment]
@simonc @scottkidder just released!

**Comment by simonc** [comment]
@AmilKey awesome! Thank you! ❤️

**Comment by scottkidder** [comment]
@AmilKey thanks very much!
